### ISSUE TITLE
Website for general data

### ISSUE THREAD

**Issue by MRegterschot** [MRegterschot/MMMSC#11]
Website where you can see the live leaderboard, search for individual tracks, perhaps mmm editions, and see the records for each of the tracks. Perhaps even player statistics, that shows improvements per day etc

**Comment by Knyntsje** [comment]
Holy what a goated idea

**Comment by Knyntsje** [comment]
Hey there! I hope you’re doing well! I wanted to check in about the website that provides data on driving times for the MMM maps. I’ve been really curious about its status lately since I love keeping up with the leaderboard and seeing how I stack up against other players.

If there are any updates or insights you can share, I’d really appreciate it. Thanks so much!

![image](https://github.com/user-attachments/assets/9e274dc5-8fbd-40d9-9db3-5696f0e244e0)

**Comment by MRegterschot** [comment]
![knyntje](https://github.com/user-attachments/assets/8741965e-4a14-4b87-89b2-1af3d2a9b2a7)

**Comment by Knyntsje** [comment]
![image](https://github.com/user-attachments/assets/3eb9b308-6054-4bf0-9167-6c6031531800)

**Comment by Knyntsje** [comment]
hoho https://mini.trackmania.events
